name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      name: "Test with ${{matrix.compiler}} ${{matrix.target}}"
      runs-on: ubuntu-latest
      matrix:
        compiler: [gcc, clang]
        target: ["BUILD=", "BUILD=release"]
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make CC=${{matrix.compiler}} ${{matrix.target}}
    - name: run tests
      run: make CC=${{matrix.compiler}} ${{matrix.target}} test
