name: Build and test

on:
  - push

jobs:
  build:
    name: "Test with ${{matrix.compiler}} ${{matrix.target}}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        target: ["BUILD=", "BUILD=release"]
    
    steps:
    - uses: actions/checkout@v1
    
    - uses: textbook/git-checkout-submodule-action@master
    
    - name: make
      run: make CC=${{matrix.compiler}} ${{matrix.target}}
    
    - name: run tests
      run: make CC=${{matrix.compiler}} ${{matrix.target}} test
